---
title: "Untitled Descriptive Project"
author:
  - Sarah Warren
date: "1/31/2022"
output: pdf_document
documentclass: paper
bibliography: references.bib
fontsize: 12
abstract: "I'll write one eventually"
header-includes:
- \usepackage[margin=1.2in]{geometry}
- \usepackage{caption}
- \usepackage{amsmath}
- \usepackage{mathrsfs}
- \usepackage{float}
- \usepackage{natbib}
- \bibliographystyle{apsr}
- \usepackage{graphicx}
- \graphicspath{ {../fig/} }
- \usepackage{setspace}
- \usepackage[super]{nth}
- \usepackage{booktabs}
- \usepackage{makecell}
- \usepackage{amsmath}
- \usepackage{dcolumn}
- \usepackage{hyperref}
- \usepackage{inputenc}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE)

library(tidyverse)
library(tidymodels)
library(ggthemes)
library(gt)
library(gtsummary)
library(ggeffects)
library(cowplot)

theme_set(theme_minimal())
dodge <- position_dodge(width=0.75)
set.seed(1234)

#function to quickly create a new column of md formatted text with significance stars from a tidy(lm()) output.
add_stars <- function(.) {	mutate(., estimate_stars = case_when(p.value > .1 ~ as.character(estimate),
															p.value <= .1 & p.value > .05 ~ paste0("__",estimate, "*__"),
															p.value <= .05 & p.value > .01 ~ paste0("__", estimate, "**__"),
															p.value <= .01 ~ paste0("__", estimate, "***__")))
}
```
\doublespacing
# Introduction
White nationalist activity is on the rise, but we still don't have a good idea of who these people are

What data we do have struggle to account for the modern digital age

Twitter data are good, but unreliable because of account bans and ToS

So what: it's hard to characterize the modern white nationalist movement as a political faction, a political party, a social movement, or a terrorist group. But we're observing a group of people who enjoy every social advantage behaving and speaking in a manner resembling a repressed group. Why?

# The StormFront Dataset
How was it collected?

What's in it?

Descriptive statistics across forums (# of posts total, average per-day, average per user)

# What are White Nationalists Saying?
Text analysis (ideally, for competitive victimhood)

  Sentiment/tone analysis
  
  Topics (via Structural Topic Modeling)
  
  Most common uni- and bi-grams
  
  Passive vs. Active voice

# When are White Nationalists Talking?
Topics over time(?)

Post length and frequency over the observation period